export enum FormaPagamentoTypeEnum {
    DINHEIRO = "DINHEIRO",
    CARTAOCREDITO = "CARTÃO DE CREDITO",
    CARTAODEBITO = "CARTÃO DE DEBITO",
    TRANSFERENCIA = "TRANSFERÊNCIA",
    CHEQUE = "CHEQUE",
    PIX = "PIX"
}